[project]
src = "src"
out = "out"
dot_env = ".env"
save_abi_path = "abis"

[networks.contracts]
weth = { abi = "abis/weth.json" }
usdc = { abi = "abis/usdc.json" }

[networks.eth-forked]
fork = true
url = "$MAINNET_RPC_URL"
default_account_name = "anvil0"

[networks.eth-forked.contracts]
usdc = { address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48" }
weth = { address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2" }